apiVersion: v1
kind: ConfigMap
metadata:
  name: labcm
  namespace: gravity2-lab
data:
  TZ: Asia/Taipei
  # MSSQL 來源配置
  SOURCE_DATABASE_NAME: source-mssql
  SOURCE_DATABASE_HOST: source-mssql
  SOURCE_DATABASE_PORT: "1433"
  SOURCE_DB_MSSQL_DB_NAME: TestDB
  SOURCE_DB_MSSQL_TB1_NAME: mi_source
  SOURCE_DATABASE_USER: SA
  # PostgreSQL 來源配置
  SOURCE_POSTGRES_NAME: source-postgres
  SOURCE_POSTGRES_HOST: source-postgres
  SOURCE_POSTGRES_PORT: "5432"
  SOURCE_POSTGRES_DB_NAME: testdb
  SOURCE_POSTGRES_TB1_NAME: source_table
  SOURCE_POSTGRES_USER: postgres
  # 目標資料庫配置
  TARGET_DB_MYSQL_NAME: target2-mysql
  TARGET_DB_MYSQL_HOST: target2-mysql
  TARGET_DB_MYSQL_PORT: "3306"
  TARGET_DB_MYSQL_DB_NAME: testdb
  TARGET_DB_MYSQL_TB1_NAME: target_id13
  TARGET_DB_MYSQL_USER: mysql
  # Git 配置
  GIT_BRANCH: main
  GIT_REPO_URL: gravity/gravity.git
  GIT_TOKEN: 241bd5bb65bed03e1efe8ebad27a74c4cf911ae7
  GIT_URL: 10.10.7.210:31300
  GIT_USER: gravity